name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '10 01 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Date'
        run: echo "CURRENT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: 'Get Love Words'
        run: echo "LOVE_WORDS=$(curl https://api.vvhan.com/api/love)" >> $GITHUB_ENV
      - name: Sending message
        uses: yakumioto/serverchan-action@v2
        with:
          key: ${{ secrets.sckey }}
          text: {${{ env.CURRENT_DATE }}}
          desp: {${{ env.LOVE_WORDS }}}
