name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '10 01 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Date'
        run: echo "CURRENT_DATE=$(TZ=':Asia/Shanghai' date '+%-m月%d日')" >> $GITHUB_ENV
      - name: 'Get Love Words'
        run: echo "LOVE_WORDS=$(curl https://api.vvhan.com/api/love)" >> $GITHUB_ENV
      - name: Sending message
        uses: yakumioto/serverchan-action@v2
        with:
          key: ${{ secrets.sckey }}
          text: ${{env.LOVE_WORDS}}的情话
          desp: ${{env.LOVE_WORDS}}
          #openid: {选填。抄送给其他关注你测试号的 openid ，多个 openid 用 , 隔开。}
