name: 'GitHub GoodNight Words Bot'

on:
  push:
  schedule:
    - cron: '30 14 * * *' # 22:00 UTC+8 every day
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Date'
        run: echo "CURRENT_DATE=$(TZ=':Asia/Shanghai' date '+%-m月%d')" >> $GITHUB_ENV
      - name: 'Get Night Words'
        run: |
          jsonval(){ temp=`echo $json | sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/\[/ /g; s/\]/ /g; ' | sed 's/\"//g' | grep -w $1|head -1`; echo ${temp}|awk -F '|' '{print $2}'; }
          json=`curl http://api.tianapi.com/txapi/wanan/index?key=${{ secrets.TIAN_API_KEY }}`
          content=`jsonval content`
          echo "NIGHT_WORDS=$content" >> $GITHUB_ENV
      - name: Sending message
        run: curl 'https://sctapi.ftqq.com/${{ secrets.SCKEY }}.send?title=${{ env.CURRENT_DATE }}深夜&desp=${{ env.NIGHT_WORDS }}&openid=${{ secrets.OPENID }}'
