name: 'GitHub GoodNight Words Bot'

on:
  push:
  schedule:
    - cron: '30 14 * * *' # 22:00 UTC+8 every day
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Date'
        run: echo "CURRENT_DATE=$(TZ=':Asia/Shanghai' date '+%-m月%d')" >> $GITHUB_ENV
      - name: 'Get Night Words'
        run: |
          bash ./goodnight.sh
          echo "NIGHT_WORDS=$(cat ./night.txt)" >> $GITHUB_ENV
      - name: Sending message
        run: curl 'https://sctapi.ftqq.com/${{ secrets.SCKEY }}.send?title=${{ env.CURRENT_DATE }}的晚安&desp=${{ env.NIGHT_WORDS }}&openid=${{ secrets.OPENID }}'
