name: 'GitHub Joke Bot'

on:
  schedule:
    - cron: '30 3 * * *' # 11:30 UTC+8 every day
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Time'
        run: echo "CURRENT_TIME=$(TZ=':Asia/Shanghai' date '+%H点%M分')" >> $GITHUB_ENV
      - name: 'Get Love Words'
        run: |
          echo "XH_WORDS=$(curl https://api.vvhan.com/api/xh | sed -n -e 'H;${x;s/\n//g;p;}')" >> $GITHUB_ENV
          echo $XH_WORDS
      - name: Sending message
        run: curl 'https://service-foq0aw19-1253137038.sh.apigw.tencentcs.com/release/weworkchan?sendkey=${{ secrets.SENDKEY }}&msg_type=text&msg=${{ env.CURRENT_TIME }}午饭时间到咯%20%20笑话一则%0D%0A%0D%0A${{ env.XH_WORDS }}&to_user=${{ secrets.TO_USER }}'