name: 'GitHub Weather Bot'

on:
  schedule:
    - cron: '30 1 * * 0,6' # 07:30 UTC+8 working day.
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Date'
        run: echo "CURRENT_DATE=$(TZ=':Asia/Shanghai' date '+%-m月%d日')" >> $GITHUB_ENV
      - name: 'Get weather info'
        run: |
          bash ./weather.sh
          echo "WEATHER=$(cat ./result.txt)" >> $GITHUB_ENV
      - name: 'Sending message'
        run: curl 'https://service-foq0aw19-1253137038.sh.apigw.tencentcs.com/release/weworkchan?sendkey=${{ secrets.SENDKEY }}&msg_type=text&msg=${{ env.CURRENT_DATE }}天气状况%0D%0A%0D%0A${{ env.WEATHER }}&to_user=${{ secrets.TO_USER }}'
